language: ruby
rvm:
  - 2.2.2
addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors
sudo: false
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer '_site/' --allow-hash-href --check-html --http-status-ignore 0
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
