name: build
on: [push, pull_request]

env:
  global:
    NOKOGIRI_USE_SYSTEM_LIBRARIES=true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Read VERSION file
      id: getversion
      run: echo "version=$(cat .ruby-version)" >> $GITHUB_OUTPUT
    - name: Install Ruby
      uses: ruby/setup-ruby@master
      with:
        ruby-version: ${{ steps.getversion.outputs.version }}
    - name: Install dependencies
      run: |
       sudo apt-get update
       sudo apt-get install libcurl4-openssl-dev
       bundle config set --local deployment 'true'
       bundle install --jobs=3 --retry=3
    - name: Run tests
      run: |
       bundle exec jekyll build
       bundle exec htmlproofer '_site/' \
         --allow-hash-href --ignore-status-codes 0,403 \
         --ignore-urls '/.*good\+first\+issue.*/,/.*matrix\.to.*/'
